### PR TITLE
libherokubuildpack: Fix colour resetting for the `log_*` macros

### LINKED ISSUE #555: Pack output eats libherokubuildpack colors
Running this command:

```
$ pack build yolo --builder schneems-22 --path /tmp/rails61 --verbose
```

We should see header colors, but they're eaten by pack. Screenshot:

Screenshot 2023-01-31 at 3 23 10 PM

Notice that the color of `[builder]` right next to `[Installing Ruby]` is different. I think what's happening is the color code is somehow being sent before `[builder]` and it sets it's own color, and then clears it. We get no color because of the clear.

I'm not sure if this is something we can fix here or need to go upstream with a bug report.

### PR DESCRIPTION
**Pull request by edmorley**
This fixes some long-standing ANSI colour bugs with the `log_header`, `log_error` and `log_warning` macros. 

Whilst we soon want to move away to more advanced logging libraries that use the new logging style, there are still many buildpacks using these macros which will benefit short term from these fixes (Procfile, Go, Node.js, JVM, Python, PHP, buildpacks-release-phase, buildpacks-frontend-web).

The logging macros would previously emit output roughly like:

```
<colour>
[Error: Foo]
<reset><colour>Message line one.
Message line two.
```

This was not only missing the final `<reset>`, but also didn't wrap each line individually with colour codes/resets.

This causes issues when lines end up prefixed - such as the Git `remote:` prefix, or when using Pack CLI locally with an untrusted build (which adds the colourised `[builder]` prefixes) or `--timestamps` mode.

For example in this:

```
remote: <colour>
remote: [Error: Foo]
remote: <reset><colour>Message line one.
remote: Message line two.
```

...several of the `remote:`s would inherit the colours.

Instead what we need is:

```
remote: <colour><reset>
remote: <colour>[Error: Foo]<reset>
remote: <colour>Message line one.<reset>
remote: <colour>Message line two.<reset>
```

Fixes #555.
Closes #844.
GUS-W-17400078.

### CODE REVIEW

**Comment by edmorley** [comment]
### Before

before

### After

after

File: libherokubuildpack/src/log.rs [hunk 1]
```diff
@@ -72,3 +74,22 @@ pub fn log_info(message: impl AsRef<str>) {
...
+// Styles each line of text separately, so that when buildpack output is streamed to the
+// user (and prefixes like `remote:` added) the line colour doesn't leak into the prefixes.
+fn write_styled_message(
+    stream: &mut StandardStream,
+    message: impl AsRef<str>,
+    spec: &ColorSpec,
+) -> io::Result<()> {
+    // Using `.split('\n')` rather than `.lines()` since the latter eats trailing newlines in
+    // the passed message, which would (a) prevent the caller from being able to add spacing at
+    // the end of their message and (b) differ from the `println!` / `writeln!` behaviour.
```
Comment (Malax) [inline libherokubuildpack/src/log.rs:87]: Nice attention to detail here :)

**Review by Malax — APPROVED** [review]
