### PR TITLE
libcnb-test: Clean up Docker volumes after each test

### LINKED ISSUE #570: Cache volumes created by Pack are not cleaned up by `libcnb-test`
I recently ran into buildpack IO errors during a `pack build` that turned out to be due to disk space exhaustion on the macOS Docker Desktop created VM - caused by leftover Docker volumes used by Pack for caching.

There were ~800 named Docker volumes that consumed 40GB of disk space, of form:

```
$ docker volume ls
DRIVER    VOLUME NAME
local     pack-cache-library_libcnbtest_abnaipzkqlhfeopwdzgpcmwnldonle_latest-ce76e11c69c4.build
local     pack-cache-library_libcnbtest_abnaipzkqlhfeopwdzgpcmwnldonle_latest-ce76e11c69c4.launch
local     pack-cache-library_libcnbtest_actqilpclbkigdmjhdrhgnuwgealsm_latest-a44e7557da8c.build
local     pack-cache-library_libcnbtest_actqilpclbkigdmjhdrhgnuwgealsm_latest-a44e7557da8c.launch
local     pack-cache-library_libcnbtest_actyjtmpayftrpdhfehpwefuffycaf_latest-d0ec397b5241.build
local     pack-cache-library_libcnbtest_actyjtmpayftrpdhfehpwefuffycaf_latest-d0ec397b5241.launch
...
```

For normal (non-integration testing) usage of Pack CLI, one wouldn't end up with hundreds of these volumes, since caches are re-used/replaced for the same output image name. The reason we end up with hundreds when using `libcnb-test` is that it uses a random image name each time (which is the right thing for it to do), but whilst it deletes the images at the end of each test, it doesn't currently delete the image's associated Pack cache volumes.

I've started a discussion upstream about some potential improvements upstream (for example, adding `pack cache prune` commands or similar, and also asking why Pack is creating these volumes for layers that also exist in the final app image):
https://cloud-native.slack.com/archives/C0331B61A1Y/p1683817627443339

However, `libcnb-test` will need to handle this even with those improvements upstream.

To avoid this issue, `libcnb-test` can use the new `--cache` argument to `pack build`, and either:
1. Continue to use volume-based caching, but pass in an explicit (and random) volume name, that `libcnb-test` can then remove when `TestContext` is dropped. (For example: `--cache='type=build;format=volume;name=<volume-name>;type=launch;format=volume;name=<volume-name>'`)
2. Or, switch to bind mount based caching, and pass in a temporary directory as the cache location, that `libcnb-test` can then remove when `TestContext` is dropped. (For example: `--cache='type=build;format=bind;source=<a-tmp-dir>;type=launch;format=bind;source=<a-tmp-dir>'`)

GUS-W-13195631.

### LINKED ISSUE #735: libcnb-test: Images are removed multiple times when using `TestContext::rebuild`
Currently `libcnb-test`'s teardown cleanup of the generated app image occurs in `TestContext::drop`. This combined with `TestContext::rebuild()` creating a brand new context means that as each of these `TestContext`s are torn down, the cleanup of images (which are the same image name for each rebuild) occurs multiple times.

To resolve this, the image name perhaps needs to be moved into a separate data type that has its own cleanup, that can be owned by the initial `TestRunner::build` call, and used by reference thereafter.

We're about to add even more teardown in order to fix #570, which raises the priority of this.

GUS-W-14503186.

### LINKED ISSUE #736: libcnb-test: Running tests when Docker daemon is not running results in noisy traceback
If I forget to start the Docker daemon and run `libcnb-test` based integration tests, I get a very noisy error message due to a panic occurring inside `TestContext::drop` causing unwinding to be aborted and a traceback being shown.

Whilst panicing inside the drop was intentionally added (when we migrated away from Bollard, where the use of tokio made panicing inside the drop even more problematic) so that failures during cleanup wouldn't go unnoticed, it does mean a slightly worse UX for scenarios like forgetting to start the Docker daemon.

eg:

```
$ cargo test -- --ignored
...

thread 'download_sbom_files_failure' panicked at /Users/emorley/src/libcnb.rs/libcnb-test/src/test_context.rs:232:43:
Error downloading SBOM files:

pack command failed with exit code 1!

## stderr:

ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

## stdout:



thread 'download_sbom_files_failure' panicked at libcnb-test/src/test_context.rs:277:43:
Error removing Docker image:

docker command failed with exit code 1!

## stderr:

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

## stdout:



stack backtrace:
   0:        0x104d83114 - std::backtrace_rs::backtrace::libunwind::trace::hc11c3e483f2379f0
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x104d83114 - std::backtrace_rs::backtrace::trace_unsynchronized::h6d90324bf9227365
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104d83114 - std::sys_common::backtrace::_print_fmt::hce6e6ec5e23f5e23
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x104d83114 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6213d4191813cce8
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x104da5448 - core::fmt::rt::Argument::fmt::hcabd205e4a0db13f
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/fmt/rt.rs:138:9
   5:        0x104da5448 - core::fmt::write::h7aa650ec429c4474
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/fmt/mod.rs:1114:21
   6:        0x104d7f604 - std::io::Write::write_fmt::h34a113e127517ce0
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/io/mod.rs:1763:15
   7:        0x104d82f54 - std::sys_common::backtrace::_print::h6973615afb577078
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x104d82f54 - std::sys_common::backtrace::print::h2c4ea7df25d490b0
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x104d84afc - std::panicking::default_hook::{{closure}}::h6a9c442831e71c54
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:272:22
  10:        0x104d8473c - std::panicking::default_hook::h1883e29001b54bb1
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:289:9
  11:        0x1048a0d28 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h79a7d8051e924ef1
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/alloc/src/boxed.rs:2021:9
  12:        0x1048a0d28 - test::test_main::{{closure}}::h0111eaf6edf85968
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/test/src/lib.rs:136:21
  13:        0x104d8517c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0535b285e4317e5e
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/alloc/src/boxed.rs:2021:9
  14:        0x104d8517c - std::panicking::rust_panic_with_hook::ha2d0c2f4cb15d266
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:735:13
  15:        0x104d84f48 - std::panicking::begin_panic_handler::{{closure}}::h1241049cf47ef05d
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:609:13
  16:        0x104d835a0 - std::sys_common::backtrace::__rust_end_short_backtrace::hf4071911b35e0226
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/sys_common/backtrace.rs:170:18
  17:        0x104d84cb4 - rust_begin_unwind
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:597:5
  18:        0x104dbd9c0 - core::panicking::panic_fmt::hc4c41dec48acd219
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/panicking.rs:72:14
  19:        0x1048af320 - <libcnb_test::test_context::TestContext as core::ops::drop::Drop>::drop::{{closure}}::hd8eb421f407157d1
                               at /Users/emorley/src/libcnb.rs/libcnb-test/src/test_context.rs:277:43
  20:        0x1048b20f8 - core::result::Result<T,E>::unwrap_or_else::hd6c9c2b0691121d6
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/result.rs:1429:23
  21:        0x1048aa174 - <libcnb_test::test_context::TestContext as core::ops::drop::Drop>::drop::h5438c46aa6367373
                               at /Users/emorley/src/libcnb.rs/libcnb-test/src/test_context.rs:276:9
  22:        0x1047d0410 - core::ptr::drop_in_place<libcnb_test::test_context::TestContext>::hca9a1f147ddcb9cb
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/ptr/mod.rs:497:1
  23:        0x10479812c - integration_test::download_sbom_files_failure::{{closure}}::h49d9e23c5ca69094
                               at /Users/emorley/src/libcnb.rs/libcnb-test/tests/integration_test.rs:442:9
  24:        0x1047ba2fc - libcnb_test::test_runner::TestRunner::build_internal::ha148969b3b33b860
                               at /Users/emorley/src/libcnb.rs/libcnb-test/src/test_runner.rs:168:9
  25:        0x1047cadb8 - libcnb_test::test_runner::TestRunner::build::h51b8f023076dd8d6
                               at /Users/emorley/src/libcnb.rs/libcnb-test/src/test_runner.rs:51:9
  26:        0x104795300 - integration_test::download_sbom_files_failure::hf43b80e67d8844b2
                               at /Users/emorley/src/libcnb.rs/libcnb-test/tests/integration_test.rs:436:5
  27:        0x1047980f8 - integration_test::download_sbom_files_failure::{{closure}}::h0955fc172df6961f
                               at /Users/emorley/src/libcnb.rs/libcnb-test/tests/integration_test.rs:435:34
  28:        0x1047cf62c - core::ops::function::FnOnce::call_once::hfc2e020976f5ec4f
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/ops/function.rs:250:5
  29:        0x1048a4bac - core::ops::function::FnOnce::call_once::h5e2546a82a9c1a98
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/ops/function.rs:250:5
  30:        0x1048a4bac - test::__rust_begin_short_backtrace::h15808fb5ba47b8da
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/test/src/lib.rs:626:18
  31:        0x1048a3c4c - test::run_test_in_process::{{closure}}::hed6912146ab4e7de
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/test/src/lib.rs:649:60
  32:        0x1048a3c4c - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55e6845689988e27
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/panic/unwind_safe.rs:271:9
  33:        0x1048a3c4c - std::panicking::try::do_call::h33fe11c28f56acc1
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:504:40
  34:        0x1048a3c4c - std::panicking::try::h4af37ab153ccddb4
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:468:19
  35:        0x1048a3c4c - std::panic::catch_unwind::he78da2c8735d17a3
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panic.rs:142:14
  36:        0x1048a3c4c - test::run_test_in_process::hc710037c056aa0ce
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/test/src/lib.rs:649:27
  37:        0x1048a3c4c - test::run_test::{{closure}}::h83a08df0d5d84953
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/test/src/lib.rs:572:43
  38:        0x104877478 - test::run_test::{{closure}}::hfdf77b75b8a327aa
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/test/src/lib.rs:600:41
  39:        0x104877478 - std::sys_common::backtrace::__rust_begin_short_backtrace::h675e32e15485cb66
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/sys_common/backtrace.rs:154:18
  40:        0x10487bbe8 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h9cf1e913344c88fb
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/thread/mod.rs:529:17
  41:        0x10487bbe8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8eb19aa4d5ef102a
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/panic/unwind_safe.rs:271:9
  42:        0x10487bbe8 - std::panicking::try::do_call::h653778a664a309d5
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:504:40
  43:        0x10487bbe8 - std::panicking::try::hf1413ab33f4e2a52
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panicking.rs:468:19
  44:        0x10487bbe8 - std::panic::catch_unwind::h306660674760c883
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/panic.rs:142:14
  45:        0x10487bbe8 - std::thread::Builder::spawn_unchecked_::{{closure}}::h394b7edd3953812d
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/thread/mod.rs:528:30
  46:        0x10487bbe8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc1a38b123ebeeb8d
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/ops/function.rs:250:5
  47:        0x104d89e74 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h094b3824d7740b88
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/alloc/src/boxed.rs:2007:9
  48:        0x104d89e74 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3f9a414dd90fc2a1
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/alloc/src/boxed.rs:2007:9
  49:        0x104d89e74 - std::sys::unix::thread::Thread::new::thread_start::h5f779a927cb6a3cb
                               at /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/std/src/sys/unix/thread.rs:108:17
  50:        0x184375034 - __pthread_joiner_wake
thread 'download_sbom_files_failure' panicked at library/core/src/panicking.rs:144:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
```

GUS-W-14503192.

### PR DESCRIPTION
**Pull request by edmorley**
When using `pack build`, by default Pack will create two Docker volumes for caching - one for the build layer cache, and the other for the launch layer cache. Pack bases the names for these volumes on the app image name, so that the next time a build is performed with the same app image name, the associated cache is used for that rebuild.

When libcnb-test runs tests, it intentionally uses a random Docker image name for each new test, and then tears down the image and any associated containers after the tests.

However, until now the Docker volumes automatically created by Pack were not being removed, which can cause issues when running the tests locally, since the Docker VM can run out of disk space - as seen in #570. The leftover volumes can also be seen in the tests log output added in #740.

Pack doesn't currently offer a "clean up the volumes associated with this app name" feature, so we have to remove these volumes manually. To do so we need the volume name - which we achieve by generating a name ourselves, and passing it to `pack build` using the `--cache` options, so Pack uses our volume name instead of generating its own automatic volume name.

Since we're now cleaning up not only images but volumes too, I've refactored the way resources are cleaned up, to reduce the amount of duplication (since otherwise we'd need to handle the "still clean up for expected failures" case for volumes too). This new implementation also solves #735 and #736.

Fixes #570.
Fixes #735.
Fixes #736.
GUS-W-13195631.
GUS-W-14503186.
GUS-W-14503192.

### CODE REVIEW

File: libcnb-test/src/test_runner.rs [hunk 1]
```diff
@@ -160,11 +159,42 @@ impl TestRunner {
...
+            docker_resources,
             config: config.clone(),
             runner: self,
         };
 
         f(test_context);
     }
 }
+
+pub(crate) struct TemporaryDockerResources {
```
Comment (edmorley) [inline libcnb-test/src/test_runner.rs:171]: I'm not super happy with the name `TemporaryDockerResources` (and also the `docker_resources` field name for `TestContext`), so open to ideas :-)

Another option might be `TemporaryBuildResources` - though "Build" is slightly overloaded in that `libcnb-test` has the `build` module and types like `BuildConfig` - which are actually referring to the Cargo build (ie compile) not the `pack build`.

(Though given this is an internal-only type I suppose it's not the end of the world if we can't find a perfect name.)

File: libcnb-test/src/test_runner.rs [hunk 2]
```diff
@@ -160,11 +159,42 @@ impl TestRunner {
...
+    pub(crate) build_cache_volume_name: String,
+    pub(crate) image_name: String,
+    pub(crate) launch_cache_volume_name: String,
+}
+
+impl TemporaryDockerResources {
+    pub fn new() -> Self {
```
Comment (Malax) [inline libcnb-test/src/test_runner.rs:178]: I think naming this function `new` is potentially confusing. I read the usage of it first (since it comes before this in the PR diff) and was wondering what would happen. I could see it either initialising it with empty-_like_ values, random names (like seen here) and actually side-effecting to do some sort of initialisation with the Docker process (and wondering what that even would be).

Finding a great alternative name for this function isn't easy - I tried to come up with a good suggestion but nothing came out of that.

However, we only create a new value of this struct _once_. This leaves us with the option of moving the body of this `new` function to the place where it's used and not giving it a name.  This has the advantage that the fact that only random names are generated and no side-effects are happening is absolutely clear at the call-site.

**Review by Malax — CHANGES_REQUESTED** [review]
I left one comment, let's discuss there - otherwise this has my approval. :)

File: libcnb-test/src/test_runner.rs (hunk 1 above)
Comment (Malax) [reply libcnb-test/src/test_runner.rs:171]: FWIW: I think this is fine as-as. :)

Comment (colincasey) [reply libcnb-test/src/test_runner.rs:178]: yeah, i see no problem with the current name.  it communicates to me that the image, build cache volume, and launch cache volume are meant to be temporary so i shouldn't see them still kicking around after a test executes.

**Review by colincasey — APPROVED** [review]

File: libcnb-test/src/test_runner.rs (hunk 2 above)
Comment (edmorley) [reply libcnb-test/src/test_runner.rs]: Agree - changed in d11167bf4b342144e51332b21f3923fea0bc6736 :-)

**Review by Malax — APPROVED** [review]
